--crear tabla 
CREATE TABLE datos_maquinaria.INDICADOR_SEMANAL (
    TOTAL_GENERAL VARCHAR (255),
    HPR FLOAT,
    DISP VARCHAR (255),
    META FLOAT,
    MTBF FLOAT,
    MTTR FLOAT,
    AVERIAS INT,
    MINUTOS FLOAT,
    OEE VARCHAR (255)
);
--TRUNCATE TABLE INDICADOR_SEMANAL; 

CREATE TABLE datos_maquinaria.INDICADOR_SEMANAL_HISTORICO_L1 (
    A±O INT,
    SEMANA INT,
    HPR FLOAT,
    DISP FLOAT,
    META FLOAT,
    MTBF FLOAT,
    MTTR FLOAT,
    AVERIAS INT,
    MINUTOS FLOAT,
    OEE FLOAT,
    PAROSMENORES BOOLEAN,
    UNIQUE (A±O, SEMANA, PAROSMENORES)
);

CREATE TABLE datos_maquinaria.INDICADOR_SEMANAL_HISTORICO_L2 (
    A±O INT,
    SEMANA INT,
    HPR FLOAT,
    DISP FLOAT,
    META FLOAT,
    MTBF FLOAT,
    MTTR FLOAT,
    AVERIAS INT,
    MINUTOS FLOAT,
    OEE FLOAT,
    PAROSMENORES BOOLEAN,
    UNIQUE (A±O, SEMANA, PAROSMENORES)
);

CREATE TABLE datos_maquinaria.INDICADOR_SEMANAL_HISTORICO_L3 (
    A±O INT,
    SEMANA INT,
    HPR FLOAT,
    DISP FLOAT,
    META FLOAT,
    MTBF FLOAT,
    MTTR FLOAT,
    AVERIAS INT,
    MINUTOS FLOAT,
    OEE FLOAT,
    PAROSMENORES BOOLEAN,
    UNIQUE (A±O, SEMANA, PAROSMENORES)
);


CREATE TABLE datos_maquinaria.INDICADOR_SEMANAL_HISTORICO_L4 (
    A±O INT,
    SEMANA INT,
    HPR FLOAT,
    DISP FLOAT,
    META FLOAT,
    MTBF FLOAT,
    MTTR FLOAT,
    AVERIAS INT,
    MINUTOS FLOAT,
    OEE FLOAT,
    PAROSMENORES BOOLEAN,
    UNIQUE (A±O, SEMANA, PAROSMENORES)
);


INSERT INTO datos_maquinaria.INDICADOR_SEMANAL (TOTAL_GENERAL, META)
SELECT DISTINCT LINEA AS TOTAL_GENERAL, 0.95 AS META
FROM datos_maquinaria.HPR_OEE
UNION
SELECT 'L2' AS TOTAL_GENERAL, 0.95 AS META
UNION
SELECT 'PLANTA' AS TOTAL_GENERAL, 0.95 AS META
ORDER BY TOTAL_GENERAL;




